log_level: verbose

database:
  dialect: "sql"
  name: "port_dev_n"
  url: "localhost:3306"
  user: "test"
  password: "Password1"

api:
  host: "0.0.0.0"
  port: 443
  timeout_keep_alive: 10
  tls_cert: "tls/port_server.cer"
  tls_key: "tls/server_key.pem"


challenge_ttl: 60
log_level: verbose # [verbose, debug, info, warning, error]
job_interval: 36